#! /bin/sh

case "$#" in
  0)
    echo "Too few arguments." >&2
    exit 1
    ;;
  1)
    case "$1" in
      copy)
        mk='mkdir -p'
        mv='cp -u'
        ;;
      link)
        mk='mkdir -p'
        mv='ln -fs'
        ;;
      help)
        mk="printf '%s\n'"
        mv="printf '%s -> %s\n'"
        ;;
      *)
        echo "Invalid argument." >&2
        exit 1
        ;;
    esac
    ;;
  *)
    echo "Too many arguments." >&2
    exit 1
    ;;
esac

root="${TEXMF-$HOME}"

from="$PWD"

to="$root/texmf/tex/latex/jyu"
eval "$mk" "$to"
eval "$mv" "$from/jyupreamble.tex" "$to"
eval "$mv" "$from/jyuseminar.cls" "$to"
eval "$mv" "$from/jyuthesis.cls" "$to"

to="$root/texmf/tex/generic/jyu"
eval "$mk" "$to"
eval "$mv" "$from/jyu-loose-english-eps-converted-to.pdf" "$to"
eval "$mv" "$from/jyu-loose-english-outline-eps-converted-to.pdf" "$to"
eval "$mv" "$from/jyu-loose-english-outline.eps" "$to"
eval "$mv" "$from/jyu-loose-english.eps" "$to"
eval "$mv" "$from/jyu-loose-eps-converted-to.pdf" "$to"
eval "$mv" "$from/jyu-loose-finnish-eps-converted-to.pdf" "$to"
eval "$mv" "$from/jyu-loose-finnish-outline-eps-converted-to.pdf" "$to"
eval "$mv" "$from/jyu-loose-finnish-outline.eps" "$to"
eval "$mv" "$from/jyu-loose-finnish.eps" "$to"
eval "$mv" "$from/jyu-loose-outline-eps-converted-to.pdf" "$to"
eval "$mv" "$from/jyu-loose-outline.eps" "$to"
eval "$mv" "$from/jyu-loose.eps" "$to"
eval "$mv" "$from/jyu-tight-english-eps-converted-to.pdf" "$to"
eval "$mv" "$from/jyu-tight-english-outline-eps-converted-to.pdf" "$to"
eval "$mv" "$from/jyu-tight-english-outline.eps" "$to"
eval "$mv" "$from/jyu-tight-english.eps" "$to"
eval "$mv" "$from/jyu-tight-eps-converted-to.pdf" "$to"
eval "$mv" "$from/jyu-tight-finnish-eps-converted-to.pdf" "$to"
eval "$mv" "$from/jyu-tight-finnish-outline-eps-converted-to.pdf" "$to"
eval "$mv" "$from/jyu-tight-finnish-outline.eps" "$to"
eval "$mv" "$from/jyu-tight-finnish.eps" "$to"
eval "$mv" "$from/jyu-tight-outline-eps-converted-to.pdf" "$to"
eval "$mv" "$from/jyu-tight-outline.eps" "$to"
eval "$mv" "$from/jyu-tight.eps" "$to"
